{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "id": "ccd0ab32",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 246
        },
        "id": "ccd0ab32",
        "outputId": "9a0d570b-8257-4735-901c-3f15a8887031"
      },
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-d1d79537-ab02-49de-b744-369b25a3b0fe\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-d1d79537-ab02-49de-b744-369b25a3b0fe\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving AccountsExport_2025-07-24.csv to AccountsExport_2025-07-24 (1).csv\n",
            "Saving Inspecie request for 20-07-2025 to 22-07-2025.csv to Inspecie request for 20-07-2025 to 22-07-2025 (1).csv\n",
            "Saving FUM Breakdown per investor for 21-07-2025.csv to FUM Breakdown per investor for 21-07-2025 (1).csv\n",
            "Saving FUM Breakdown per investor for 22-07-2025.csv to FUM Breakdown per investor for 22-07-2025 (1).csv\n",
            "Saving Applications and redemptions for 21-07-2025 to 22-07-2025.csv to Applications and redemptions for 21-07-2025 to 22-07-2025 (1).csv\n",
            "Saving FeesListExport_22-07-2025.csv to FeesListExport_22-07-2025 (1).csv\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_e92327b5-4866-46f5-bf90-a1048f38359d\", \"Final_FUM_Report.csv\", 3506)"
            ]
          },
          "metadata": {}
        }
      ],
      "source": [
        "# --- Upload and Load Files Dynamically ---\n",
        "from google.colab import files\n",
        "import pandas as pd\n",
        "import io\n",
        "import re\n",
        "from datetime import datetime\n",
        "\n",
        "uploaded = files.upload()\n",
        "\n",
        "fum_files = {}\n",
        "\n",
        "# Dynamically assign files based on keywords in filename\n",
        "for filename in uploaded.keys():\n",
        "    if 'FeesList' in filename:\n",
        "        fees_df = pd.read_csv(io.BytesIO(uploaded[filename]))\n",
        "    elif 'AccountsExport' in filename:\n",
        "        investor_df = pd.read_csv(io.BytesIO(uploaded[filename]))\n",
        "    elif 'FUM Breakdown' in filename:\n",
        "        # Corrected regex: match date like 18-06-2025\n",
        "        match = re.search(r'(\\d{2}-\\d{2}-\\d{4})', filename)\n",
        "        if match:\n",
        "            file_date = datetime.strptime(match.group(1), \"%d-%m-%Y\")\n",
        "            fum_files[file_date] = pd.read_csv(io.BytesIO(uploaded[filename]))\n",
        "    elif 'Applications and redemptions' in filename:\n",
        "        txn_df = pd.read_csv(io.BytesIO(uploaded[filename]))\n",
        "    elif 'Inspecie request' in filename:\n",
        "        inspecie_df = pd.read_csv(io.BytesIO(uploaded[filename]))\n",
        "\n",
        "# Identify current and old FUM files by date\n",
        "sorted_dates = sorted(fum_files.keys())\n",
        "fum_old_df = fum_files[sorted_dates[0]]\n",
        "fum_current_df = fum_files[sorted_dates[1]]\n",
        "\n",
        "FUM_THRESHOLD = 100.0  # Set your own value\n",
        "fum_current_df = fum_current_df[fum_current_df['Current Value'] >= FUM_THRESHOLD].copy()\n",
        "fum_old_df = fum_old_df[fum_old_df['Current Value'] >= FUM_THRESHOLD].copy()\n",
        "\n",
        "# --- Map Investors to Services ---\n",
        "import numpy as np\n",
        "\n",
        "\n",
        "investor_accounts = investor_df[investor_df[\"AccountCategory\"] == \"Investor Account\"].copy()\n",
        "\n",
        "# --- Clean ModelPortfolioCode so 'N/A', blanks, and whitespace all become np.nan ---\n",
        "investor_accounts['ModelPortfolioCode'] = investor_accounts['ModelPortfolioCode']\\\n",
        "    .astype(str).str.strip().replace(['', 'N/A', 'nan'], np.nan)\n",
        "\n",
        "# Optional: also clean Subdivision (in case it’s dirty too)\n",
        "investor_accounts['Subdivision'] = investor_accounts['Subdivision'].astype(str).str.strip()\n",
        "fees_df['SubdivisionDesc'] = fees_df['SubdivisionDesc'].astype(str).str.strip()\n",
        "fees_df['ModelCode'] = fees_df['ModelCode'].astype(str).str.strip()\n",
        "fees_df['FeeOwnerName'] = fees_df['FeeOwnerName'].astype(str).str.strip()\n",
        "\n",
        "# --- Merge using ModelPortfolioCode ---\n",
        "model_merge = pd.merge(\n",
        "    investor_accounts[investor_accounts['ModelPortfolioCode'].notna()],\n",
        "    fees_df[['ModelCode', 'FeeOwnerName', 'SubdivisionDesc']],\n",
        "    left_on='ModelPortfolioCode',\n",
        "    right_on='ModelCode',\n",
        "    how='left'\n",
        ")\n",
        "\n",
        "# --- Merge using Subdivision as fallback when ModelPortfolioCode is missing or 'N/A' ---\n",
        "subdivision_merge = pd.merge(\n",
        "    investor_accounts[investor_accounts['ModelPortfolioCode'].isna()],\n",
        "    fees_df[['SubdivisionDesc']],\n",
        "    left_on='Subdivision',\n",
        "    right_on='SubdivisionDesc',\n",
        "    how='left'\n",
        ")\n",
        "\n",
        "# --- Final assignments ---\n",
        "model_merge['ServiceName'] = model_merge['FeeOwnerName']\n",
        "subdivision_merge['ServiceName'] = subdivision_merge['Subdivision']\n",
        "combined_df_corrected = pd.concat([model_merge, subdivision_merge], ignore_index=True)\n",
        "service_dictionary = combined_df_corrected[['AccountCode', 'ServiceName', 'Subdivision']].drop_duplicates()\n",
        "\n",
        "# --- 🔍 Optional: Identify unmatched accounts ---\n",
        "matched_accounts = pd.concat([model_merge['AccountCode'], subdivision_merge['AccountCode']])\n",
        "unmatched_accounts = investor_accounts[~investor_accounts['AccountCode'].isin(matched_accounts)]\n",
        "if not unmatched_accounts.empty:\n",
        "    print(\"⚠️ Warning: Some accounts were not matched to any service:\")\n",
        "    display(unmatched_accounts[['AccountCode', 'ModelPortfolioCode', 'Subdivision']])\n",
        "\n",
        "# --- Prep FUM ---\n",
        "fum_current_df['AccountCode'] = fum_current_df['Account Code'].str.strip()\n",
        "fum_old_df['AccountCode'] = fum_old_df['Account Code'].str.strip()\n",
        "new_accounts = set(fum_current_df['AccountCode']) - set(fum_old_df['AccountCode'])\n",
        "closed_accounts = set(fum_old_df['AccountCode']) - set(fum_current_df['AccountCode'])\n",
        "\n",
        "fum_current_df['NewAccountFlag'] = fum_current_df['AccountCode'].isin(new_accounts)\n",
        "fum_old_df['ClosedAccountFlag'] = fum_old_df['AccountCode'].isin(closed_accounts)\n",
        "\n",
        "fum_current_labeled = pd.merge(fum_current_df, service_dictionary, on='AccountCode', how='left')\n",
        "fum_old_labeled = pd.merge(fum_old_df, service_dictionary, on='AccountCode', how='left')\n",
        "\n",
        "current_summary = fum_current_labeled.groupby('ServiceName').agg(\n",
        "    TotalFUMHeldToday=('Current Value', 'sum'),\n",
        "    TotalAccountsToday=('AccountCode', 'count'),\n",
        "    NewAccounts=('NewAccountFlag', 'sum')\n",
        ").reset_index()\n",
        "\n",
        "closed_df = fum_old_labeled[fum_old_labeled['ClosedAccountFlag']]\n",
        "closed_summary = closed_df.groupby('ServiceName').agg(\n",
        "    AccountClosures=('AccountCode', 'count')\n",
        ").reset_index()\n",
        "\n",
        "old_fum_totals = fum_old_labeled.groupby('ServiceName').agg(\n",
        "    TotalFUMHeldPrevious=('Current Value', 'sum')\n",
        ").reset_index()\n",
        "\n",
        "fum_summary = pd.merge(current_summary, closed_summary, on='ServiceName', how='left').fillna(0)\n",
        "fum_summary = pd.merge(fum_summary, old_fum_totals, on='ServiceName', how='left')\n",
        "\n",
        "fum_summary['GrowthInFUM (%)'] = (\n",
        "    (fum_summary['TotalFUMHeldToday'] - fum_summary['TotalFUMHeldPrevious']) /\n",
        "    fum_summary['TotalFUMHeldPrevious'].replace({0: pd.NA})\n",
        ") * 100\n",
        "\n",
        "# --- Deposits and Withdrawals ---\n",
        "txn_df.rename(columns={\n",
        "    'Account Code': 'AccountCode',\n",
        "    'Cash Transaction Type': 'TransactionType',\n",
        "    'Tranaction Value': 'TransactionValue'\n",
        "}, inplace=True)\n",
        "\n",
        "account_flags = fum_current_df[['AccountCode', 'NewAccountFlag']]\n",
        "txn_merged = pd.merge(txn_df, account_flags, on='AccountCode', how='left')\n",
        "txn_merged['NewAccountFlag'] = txn_merged['NewAccountFlag'].fillna(False)\n",
        "txn_merged = pd.merge(txn_merged, service_dictionary, on='AccountCode', how='left')\n",
        "\n",
        "# Make withdrawals negative BEFORE grouping\n",
        "#txn_merged.loc[txn_merged['TransactionType'].str.lower() == 'withdrawal', 'TransactionValue'] *= -1\n",
        "\n",
        "# Split by transaction type\n",
        "deposits = txn_merged[txn_merged['TransactionType'].str.lower() == 'deposit']\n",
        "withdrawals = txn_merged[txn_merged['TransactionType'].str.lower() == 'withdrawal']\n",
        "\n",
        "deposit_summary = deposits.groupby('ServiceName').agg(\n",
        "    TotalDeposits=('TransactionValue', 'sum'),\n",
        "    TotalDepositsNew=('TransactionValue', lambda x: x[deposits['NewAccountFlag']].sum()),\n",
        "    TotalDepositsPresent=('TransactionValue', lambda x: x[~deposits['NewAccountFlag']].sum())\n",
        ").reset_index()\n",
        "\n",
        "withdrawal_summary = withdrawals.groupby('ServiceName').agg(\n",
        "    TotalWithdrawals=('TransactionValue', 'sum')\n",
        ").reset_index()\n",
        "\n",
        "txn_summary = pd.merge(deposit_summary, withdrawal_summary, on='ServiceName', how='outer').fillna(0)\n",
        "\n",
        "\n",
        "# --- Inspecie ---\n",
        "inspecie_df.rename(columns={'Account code': 'AccountCode'}, inplace=True)\n",
        "inspecie_df['Value'] = pd.to_numeric(inspecie_df['Value'], errors='coerce')\n",
        "\n",
        "inspecie_merged = pd.merge(inspecie_df, service_dictionary, on='AccountCode', how='left')\n",
        "inspecie_merged['InspecieIn'] = inspecie_merged['Value'].where(inspecie_merged['Value'] > 0, 0)\n",
        "inspecie_merged['InspecieOut'] = inspecie_merged['Value'].where(inspecie_merged['Value'] < 0, 0)\n",
        "\n",
        "inspecie_summary = inspecie_merged.groupby('ServiceName').agg(\n",
        "    TotalInspecieIn=('InspecieIn', 'sum'),\n",
        "    TotalInspecieOut=('InspecieOut', 'sum')\n",
        ").reset_index()\n",
        "\n",
        "# --- Combine All ---\n",
        "final_report = pd.merge(fum_summary, txn_summary, on='ServiceName', how='left')\n",
        "final_report = pd.merge(final_report, inspecie_summary, on='ServiceName', how='left')\n",
        "final_report = final_report.fillna(0)\n",
        "\n",
        "# ----------------------\n",
        "# Define column groups\n",
        "# ----------------------\n",
        "dollar_cols = [\n",
        "    'TotalFUMHeldToday', 'TotalFUMHeldPrevious', 'TotalDeposits', 'TotalDepositsNew',\n",
        "    'TotalDepositsPresent', 'TotalWithdrawals', 'TotalInspecieIn', 'TotalInspecieOut'\n",
        "]\n",
        "\n",
        "int_cols = ['TotalAccountsToday', 'NewAccounts', 'AccountClosures']\n",
        "\n",
        "# ----------------------\n",
        "# Convert dollar and int cols to float/int for processing\n",
        "# ----------------------\n",
        "for col in dollar_cols:\n",
        "    final_report[col] = final_report[col].astype(float)\n",
        "\n",
        "for col in int_cols:\n",
        "    final_report[col] = final_report[col].astype(int)\n",
        "\n",
        "# ----------------------\n",
        "# Calculate Totals Row\n",
        "# ----------------------\n",
        "totals_row = {\n",
        "    'ServiceName': 'TOTAL',\n",
        "    'TotalFUMHeldToday': final_report['TotalFUMHeldToday'].sum(),\n",
        "    'TotalFUMHeldPrevious': final_report['TotalFUMHeldPrevious'].sum(),\n",
        "    'TotalDeposits': final_report['TotalDeposits'].sum(),\n",
        "    'TotalDepositsNew': final_report['TotalDepositsNew'].sum(),\n",
        "    'TotalDepositsPresent': final_report['TotalDepositsPresent'].sum(),\n",
        "    'TotalWithdrawals': final_report['TotalWithdrawals'].sum(),\n",
        "    'TotalInspecieIn': final_report['TotalInspecieIn'].sum(),\n",
        "    'TotalInspecieOut': final_report['TotalInspecieOut'].sum(),\n",
        "    'TotalAccountsToday': final_report['TotalAccountsToday'].sum(),\n",
        "    'NewAccounts': final_report['NewAccounts'].sum(),\n",
        "    'AccountClosures': final_report['AccountClosures'].sum(),\n",
        "}\n",
        "\n",
        "# Growth in FUM based on totals\n",
        "fum_today = totals_row['TotalFUMHeldToday']\n",
        "fum_prev = totals_row['TotalFUMHeldPrevious']\n",
        "growth = ((fum_today - fum_prev) / fum_prev * 100) if fum_prev != 0 else 0\n",
        "totals_row['GrowthInFUM (%)'] = growth\n",
        "\n",
        "# Append totals\n",
        "final_report = pd.concat([final_report, pd.DataFrame([totals_row])], ignore_index=True)\n",
        "\n",
        "# ----------------------\n",
        "# Formatting\n",
        "# ----------------------\n",
        "\n",
        "# Format dollar columns\n",
        "for col in dollar_cols:\n",
        "    final_report[col] = final_report[col].apply(lambda x: f\"${float(x):,.2f}\")\n",
        "\n",
        "# Format integer columns (handle TOTAL row gracefully)\n",
        "for col in int_cols:\n",
        "    final_report[col] = final_report[col].apply(lambda x: f\"{int(x)}\" if str(x).isdigit() else x)\n",
        "\n",
        "# Format percentage column\n",
        "final_report['GrowthInFUM (%)'] = final_report['GrowthInFUM (%)'].apply(\n",
        "    lambda x: f\"{float(x):.2f}%\" if str(x).replace('.', '', 1).replace('-', '').isdigit() else x\n",
        ")\n",
        "\n",
        "# ----------------------\n",
        "# Sort so TOTAL row is at the bottom\n",
        "# ----------------------\n",
        "final_report['SortOrder'] = final_report['ServiceName'].apply(lambda x: 1 if x != 'TOTAL' else 2)\n",
        "final_report = final_report.sort_values(['SortOrder', 'ServiceName']).drop(columns='SortOrder')\n",
        "\n",
        "# Drop rows with 0 total FUM unless it's the TOTAL row\n",
        "final_report = final_report[\n",
        "    ~((final_report['TotalFUMHeldToday'].replace('[\\\\$,]', '', regex=True).astype(float) == 0) &\n",
        "      (final_report['TotalFUMHeldPrevious'].replace('[\\\\$,]', '', regex=True).astype(float) == 0) &\n",
        "      (final_report['ServiceName'] != 'TOTAL'))\n",
        "]\n",
        "\n",
        "# ----------------------\n",
        "# Export\n",
        "# ----------------------\n",
        "final_report.to_csv(\"Final_FUM_Report.csv\", index=False)\n",
        "\n",
        "from google.colab import files\n",
        "files.download(\"Final_FUM_Report.csv\")\n",
        "\n"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "language_info": {
      "name": "python"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
